name: cgatshowcase-env
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
  - cgat
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - alignlib-lite=0.3=py36h09b0a5c_1
  - asn1crypto=0.24.0=py36_1003
  - bcftools=1.9=h4da6232_0
  - bcrypt=3.1.4=py36h470a237_0
  - bedtools=2.27.1=he941832_2
  - bioconductor-annotate=1.58.0=r341_0
  - bioconductor-annotationdbi=1.42.1=r341_0
  - bioconductor-biobase=2.40.0=r341h470a237_0
  - bioconductor-biocgenerics=0.26.0=r341_0
  - bioconductor-biocparallel=1.14.2=r341h26a2512_0
  - bioconductor-biomart=2.36.1=r341_0
  - bioconductor-clusterprofiler=3.8.1=r341_0
  - bioconductor-delayedarray=0.6.6=r341_0
  - bioconductor-deseq2=1.18.1=r3.4.1_1
  - bioconductor-do.db=2.9=r341_3
  - bioconductor-dose=3.6.1=r341_0
  - bioconductor-enrichplot=1.0.2=r341_0
  - bioconductor-fgsea=1.6.0=r341hfc679d8_0
  - bioconductor-genefilter=1.62.0=r341h26a2512_0
  - bioconductor-geneplotter=1.58.0=r341_0
  - bioconductor-genomeinfodb=1.14.0=r3.4.1_0
  - bioconductor-genomeinfodbdata=1.1.0=r341_0
  - bioconductor-genomicranges=1.30.3=r3.4.1_0
  - bioconductor-go.db=3.6.0=r341_0
  - bioconductor-gosemsim=2.6.2=r341hfc679d8_0
  - bioconductor-iranges=2.14.12=r341h470a237_0
  - bioconductor-limma=3.36.5=r341h470a237_0
  - bioconductor-org.hs.eg.db=3.6.0=r341_0
  - bioconductor-qvalue=2.12.0=r341_0
  - bioconductor-rhdf5=2.24.0=r341hfc679d8_0
  - bioconductor-rhdf5lib=1.2.1=r341h470a237_0
  - bioconductor-s4vectors=0.18.3=r341h470a237_0
  - bioconductor-summarizedexperiment=1.8.0=r3.4.1_0
  - bioconductor-tximport=1.8.0=r341_0
  - bioconductor-xvector=0.20.0=r341h470a237_0
  - bioconductor-zlibbioc=1.26.0=r341h470a237_0
  - biopython=1.70=np112py36_1
  - blas=1.1=openblas
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.14.10=0
  - certifi=2019.3.9=py36_0
  - cffi=1.11.5=py36h5e8e0c9_1
  - cgat-apps=0.5.3=py36hc40942e_0
  - cgatcore=0.5.10=py36_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - colormath=3.0.0=py_2
  - coreutils=8.25=1
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - curl=7.63.0=h74213dd_0
  - cycler=0.10.0=py_1
  - cython=0.29.2=py36hfc679d8_0
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - drmaa=0.7.9=py_1000
  - expat=2.2.5=hfc679d8_2
  - fontconfig=2.12.6=0
  - freetype=2.8.1=hfa320df_1
  - future=0.17.1=py36_1000
  - gettext=0.19.8.1=h5e8e0c9_1
  - gevent=1.1rc4=py36_0
  - glib=2.55.0=h464dc38_2
  - gmp=6.1.2=0
  - graphite2=1.3.13=hfc679d8_0
  - greenlet=0.4.13=py36_0
  - grep=2.14=h470a237_2
  - gsl=2.1=2
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h61a6719_0
  - harfbuzz=1.7.6=0
  - hdf5=1.10.3=hc401514_2
  - htslib=1.9=hc238db4_4
  - icu=58.2=0
  - idna=2.8=py36_1000
  - intel-openmp=2019.1=144
  - jinja2=2.10=py_1
  - jpeg=9c=h470a237_1
  - kallisto=0.45.0=hdcc98e5_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - krb5=1.16.3=hbb41f41_0
  - libcurl=7.63.0=hbdb9355_0
  - libdeflate=1.0=h470a237_0
  - libedit=3.1.20170329=0
  - libffi=3.2.1=hfc679d8_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h470a237_4
  - libpng=1.6.34=ha92aebf_2
  - libssh2=1.8.0=h5b517e9_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he6b73bb_2
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - lzo=2.10=0
  - lzstring=1.0.3=py36_0
  - markdown=2.6.11=py_0
  - markupsafe=1.1.0=py36h470a237_0
  - matplotlib=2.2.2=py36_1
  - mkl=2018.0.3=1
  - mmtf-python=1.1.2=py_0
  - msgpack-python=0.6.0=py36h2d50403_0
  - multiqc=1.7=py_1
  - mysql-connector-c=6.1.6=2
  - ncurses=5.9=10
  - networkx=2.0=py36_1
  - nomkl=3.0=0
  - numpy=1.12.1=py36_blas_openblashb06ca3d_1
  - olefile=0.46=py_0
  - openblas=0.3.3=h9ac9557_1001
  - openssl=1.0.2r=h14c3975_0
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.5=0
  - pango=1.40.14=0
  - paramiko=2.4.2=py36_1000
  - pcre=8.39=0
  - pillow=5.2.0=py36h2dc6135_1
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - pthread-stubs=0.4=h470a237_1
  - pyasn1=0.4.4=py_1
  - pybedtools=0.8.0=py36ha92aebf_0
  - pybigwig=0.3.12=py36hdfb72b2_0
  - pycparser=2.19=py_0
  - pynacl=1.3.0=py36_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.0=py_0
  - pyqt=5.6.0=py36h8210e8a_8
  - pysam=0.15.1=py36h0380709_0
  - pysocks=1.6.8=py36_1002
  - python=3.6.5=1
  - python-dateutil=2.7.5=py_0
  - python-lzo=1.12=py36h0480d78_0
  - pytz=2018.9=py_0
  - pyyaml=3.13=py36h470a237_1
  - qt=5.6.2=7
  - quicksect=0.2.0=py36h470a237_1
  - r-acepack=1.4.1=r341h364d78e_2
  - r-assertthat=0.2.0=r341h6115d3f_1
  - r-backports=1.1.2=r341h470a237_1
  - r-base=3.4.1=4
  - r-base64enc=0.1_3=r341hc070d10_2
  - r-bh=1.66.0_1=r341_1001
  - r-bindr=0.1.1=r341h6115d3f_1
  - r-bindrcpp=0.2.2=r341h9d2a408_1
  - r-bit=1.1_12=r341h470a237_2
  - r-bit64=0.9_7=r341hc070d10_0
  - r-bitops=1.0_6=r341hc070d10_2
  - r-blob=1.1.1=r341_1
  - r-broom=0.5.0=r341h6115d3f_2
  - r-callr=3.0.0=r341h6115d3f_0
  - r-catools=1.17.1.1=r341h9d2a408_2
  - r-cellranger=1.1.0=r341h6115d3f_1
  - r-checkmate=1.8.5=r341hc070d10_2
  - r-cli=1.0.0=r341h6115d3f_1
  - r-clipr=0.4.1=r341h6115d3f_1
  - r-cluster=2.0.7_1=r341h364d78e_0
  - r-colorspace=1.3_2=r341hc070d10_2
  - r-cowplot=0.9.3=r341h6115d3f_1
  - r-crayon=1.3.4=r341h6115d3f_1
  - r-crosstalk=1.0.0=r341h6115d3f_1
  - r-curl=3.2=r341hc070d10_2
  - r-data.table=1.11.6=r341hc070d10_0
  - r-dbi=1.0.0=r341h6115d3f_1
  - r-dbplyr=1.2.2=r341h6115d3f_1
  - r-digest=0.6.18=r341hc070d10_0
  - r-dplyr=0.7.6=r341h9d2a408_1
  - r-dt=0.4=r341h6115d3f_1
  - r-evaluate=0.11=r341h6115d3f_0
  - r-fansi=0.3.0=r341hc070d10_0
  - r-farver=1.0=r341h9d2a408_0
  - r-fastmatch=1.1_0=r341hc070d10_3
  - r-forcats=0.3.0=r341h6115d3f_1
  - r-foreign=0.8_71=r341hc070d10_2
  - r-formatr=1.5=r341h6115d3f_1
  - r-formula=1.2_3=r341h6115d3f_1
  - r-futile.logger=1.4.3=r341h6115d3f_1
  - r-futile.options=1.0.1=r341h6115d3f_0
  - r-gdata=2.18.0=r341h6115d3f_1
  - r-getopt=1.20.2=r341_1
  - r-ggforce=0.1.2=r341h9d2a408_1
  - r-ggplot2=3.1.0=r341h6115d3f_0
  - r-ggraph=1.0.2=r341h9d2a408_2
  - r-ggrepel=0.8.0=r341h9d2a408_2
  - r-ggridges=0.5.0=r341h6115d3f_1
  - r-glue=1.3.0=r341h470a237_2
  - r-gplots=3.0.1=r341h6115d3f_1
  - r-gridextra=2.3=r341h6115d3f_1
  - r-gtable=0.2.0=r341h6115d3f_1
  - r-gtools=3.8.1=r341hc070d10_2
  - r-haven=1.1.2=r341h9d2a408_2
  - r-highr=0.7=r341h6115d3f_1
  - r-hmisc=4.1_1=r341h364d78e_1
  - r-hms=0.4.2=r341h6115d3f_0
  - r-htmltable=1.12=r341h6115d3f_0
  - r-htmltools=0.3.6=r341hfc679d8_2
  - r-htmlwidgets=1.2=r341h6115d3f_0
  - r-httpuv=1.4.5=r341hfc679d8_1
  - r-httr=1.3.1=r341h6115d3f_1
  - r-igraph=1.2.2=r341he0ffe0d_1
  - r-jsonlite=1.5=r341hc070d10_2
  - r-kernsmooth=2.23_15=r341h364d78e_2
  - r-knitr=1.20=r341h6115d3f_1
  - r-labeling=0.3=r341h6115d3f_1
  - r-lambda.r=1.2.3=r341h6115d3f_0
  - r-later=0.7.3=r341h9d2a408_0
  - r-lattice=0.20_35=r341hc070d10_0
  - r-latticeextra=0.6_28=r341h6115d3f_1
  - r-lazyeval=0.2.1=r341hc070d10_2
  - r-locfit=1.5_9.1=r341h470a237_2
  - r-lubridate=1.7.4=r341hfc679d8_1
  - r-magrittr=1.5=r341h6115d3f_1
  - r-markdown=0.8=r341hc070d10_3
  - r-mass=7.3_50=r341hc070d10_2
  - r-matrix=1.2_14=r341hc070d10_2
  - r-matrixstats=0.54.0=r341hc070d10_0
  - r-memoise=1.1.0=r341h6115d3f_1
  - r-mgcv=1.8_24=r341hc070d10_2
  - r-mime=0.5=r341hc070d10_2
  - r-modelr=0.1.2=r341h6115d3f_1
  - r-munsell=0.5.0=r341h6115d3f_1
  - r-nlme=3.1_137=r341h364d78e_0
  - r-nnet=7.3_12=r341hc070d10_2
  - r-openssl=1.0.2=r341h9f97512_0
  - r-optparse=1.6.0=r341_1
  - r-pheatmap=1.0.10=r341h6115d3f_1
  - r-pillar=1.3.0=r341h6115d3f_0
  - r-pkgconfig=2.0.2=r341h6115d3f_1
  - r-plogr=0.2.0=r341h6115d3f_1
  - r-plyr=1.8.4=r341h9d2a408_2
  - r-prettyunits=1.0.2=r341h6115d3f_1
  - r-processx=3.2.0=r341hc070d10_1
  - r-progress=1.2.0=r341h6115d3f_2
  - r-promises=1.0.1=r341h9d2a408_0
  - r-ps=1.1.0=r341hc070d10_1
  - r-purrr=0.2.5=r341hc070d10_1
  - r-r6=2.2.2=r341h6115d3f_1
  - r-rcolorbrewer=1.1_2=r341h6115d3f_1
  - r-rcpp=1.0.0=r341h9d2a408_0
  - r-rcpparmadillo=0.9.100.5.0=r341h9d2a408_0
  - r-rcurl=1.95_4.11=r341hc070d10_3
  - r-readr=1.1.1=r341h9d2a408_2
  - r-readxl=1.1.0=r341h9d2a408_2
  - r-rematch=1.0.1=r341h6115d3f_1
  - r-reprex=0.2.0=r341h6115d3f_1
  - r-reshape2=1.4.3=r341h9d2a408_2
  - r-rjson=0.2.20=r341h9d2a408_0
  - r-rlang=0.3.0.1=r341h470a237_0
  - r-rmarkdown=1.10=r341h6115d3f_1
  - r-rpart=4.1_13=r341hc070d10_2
  - r-rprojroot=1.3_2=r341h6115d3f_1
  - r-rsqlite=2.1.1=r341h9d2a408_0
  - r-rstudioapi=0.7=r341h6115d3f_1
  - r-rvcheck=0.1.0=r341_1
  - r-rvest=0.3.2=r341h6115d3f_1
  - r-scales=1.0.0=r341h9d2a408_1
  - r-selectr=0.4_1=r341h6115d3f_0
  - r-shiny=1.2.0=r341_0
  - r-snow=0.4_3=r341h6115d3f_0
  - r-sourcetools=0.1.7=r341hfc679d8_0
  - r-stringi=1.2.4=r341h9d2a408_1
  - r-stringr=1.3.1=r341h6115d3f_1
  - r-survival=2.42_6=r341hc070d10_1
  - r-tibble=1.4.2=r341hc070d10_2
  - r-tidyr=0.8.1=r341h9d2a408_2
  - r-tidyselect=0.2.4=r341h9d2a408_2
  - r-tidyverse=1.2.1=r341h6115d3f_1
  - r-tinytex=0.8=r341h6115d3f_0
  - r-tweenr=1.0.0=r341h9d2a408_0
  - r-units=0.6_1=r341h9d2a408_0
  - r-upsetr=1.3.3=r341_1
  - r-utf8=1.1.4=r341hc070d10_0
  - r-viridis=0.5.1=r341h6115d3f_1
  - r-viridislite=0.3.0=r341h6115d3f_1
  - r-whisker=0.3_2=r341h6115d3f_1
  - r-withr=2.1.2=r341h6115d3f_0
  - r-xfun=0.3=r341h6115d3f_1
  - r-xml=3.98_1.16=r341hc070d10_0
  - r-xml2=1.2.0=r341h9d2a408_2
  - r-xtable=1.8_3=r341_1000
  - r-yaml=2.2.0=r341hc070d10_1
  - readline=7.0=0
  - reportlab=3.4.0=py36hdd9f355_1
  - requests=2.21.0=py36_1000
  - ruffus=2.8.1=py_0
  - samtools=1.9=h46bd0b3_0
  - scipy=1.2.0=py36_blas_openblashb06ca3d_200
  - setuptools=40.6.3=py36_0
  - simplejson=3.8.1=py36_0
  - sip=4.18.1=py36hfc679d8_0
  - six=1.12.0=py36_1000
  - spectra=0.0.11=py_0
  - sqlalchemy=1.2.15=py36h470a237_0
  - sqlite=3.20.1=2
  - time=1.7=0
  - tk=8.6.9=ha92aebf_0
  - tornado=5.1.1=py36h470a237_0
  - ucsc-bedgraphtobigwig=366=h5eb252a_0
  - ucsc-bedtobigbed=366=h5eb252a_0
  - ucsc-wigtobigwig=366=h5eb252a_0
  - udunits2=2.2.27.6=h3a4f0e9_1
  - urllib3=1.24.1=py36_1000
  - wget=1.19.5=h1ad7b7a_0
  - wheel=0.32.3=py36_0
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - zlib=1.2.11=h470a237_4
  - pip:
    - cgatshowcase==0.1.9

